language: node_js
sudo: required
install: yarn
node_js:
  - "10"
  - "11"
  - "12"
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  - npm i -g eslint
jobs:
  include:
    - stage: test
      script: yarn lint
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false