language: node_js
sudo: required
install: yarn
node_js:
  - "10"
  - "11"
  - "12"
before_install:
  - npm i -g eslint
jobs:
  include:
    - stage: test
      script: npm run lint
cache:
  yarn: true
  directories:
    - node_modules
notifications:
  email: false